### ISSUE TITLE
ansible.cfg formatting

### ISSUE THREAD

**Issue by storm49152** [CumulusNetworks/cl-piat#9]
Hi,

In ansible.cfg, shouldn't line 14 be merged with line 13?

```
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
PreferredAuthentications=publickey
```
->
```
ssh_args = -o ControlMaster=auto -o ControlPersist=60s PreferredAuthentications=publickey
```

**Comment by packetninja** [comment]
You are correct, thank you!

I've committed the change.

**Comment by storm49152** [comment]
Oops, it does cause an error, my bad. However, according to "man ssh_config" PreferredAuthentications is an ssh_arg and so should be passed as an option to it, right? For me, this does not result in a failure:

`ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey`

Can you confirm that?
